### ISSUE TITLE
--chart not working

### ISSUE THREAD

**Issue by emansammuta100533** [jesse-ai/jesse#5]
I tried the --chart parameter and got this as an exception whilst --tradingview is working fine.

`  File "c:\programdata\anaconda3\lib\site-packages\jesse\__init__.py", line 286, in backtest
    backtest_mode.run(start_date, finish_date, chart=chart, tradingview=tradingview)
  File "c:\programdata\anaconda3\lib\site-packages\jesse\modes\backtest_mode\__init__.py", line 71, in run
    charts.portfolio_vs_asset_returns()
  File "c:\programdata\anaconda3\lib\site-packages\jesse\services\charts.py", line 111, in portfolio_vs_asset_returns
    plt.savefig(file_path)
  File "c:\programdata\anaconda3\lib\site-packages\matplotlib\pyplot.py", line 722, in savefig
    res = fig.savefig(*args, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\matplotlib\figure.py", line 2180, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\matplotlib\backend_bases.py", line 2089, in print_figure
    **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 530, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "c:\programdata\anaconda3\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "c:\programdata\anaconda3\lib\site-packages\matplotlib\cbook\__init__.py", line 447, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "c:\programdata\anaconda3\lib\site-packages\matplotlib\cbook\__init__.py", line 432, in to_filehandle
    fh = open(fname, flag, encoding=encoding)

 Uncaught Exception: OSError: [Errno 22] Invalid argument: 'storage/charts/BT-2020-04-18T16:56:53.png'`

Also, what value is the qty exactly, in the case of BTCUSDT, does 1 qty mean opening a trade for 1 BTC or 1$?

I apologize for the number of opened issues but I'm migrating my algorithm to this framework and finding issues / questions as I go along but other than that quite impressed by how it all works :)

Thanks.

**Comment by firesurf** [comment]
#6 should fix it. Its a windows issue. Windows doesn't like ":" in filenames.

**Comment by saleh-mir** [comment]
Markus'es PR fixed it. I released it a new version (`0.0.17) on PyPi. To update:
```
pip install -U Jesse
```
Sometimes you have to run more than once because of a cache problem with Pypi. 

> Also, what value is the qty exactly, in the case of BTCUSDT, does 1 qty mean opening a trade for 1 BTC or 1$?

1 BTC. I personally use [risk_to_qty](https://docs.jesse-ai.com/docs/utils.html#risk-to-qty) for position sizing. 

> I apologize for the number of opened issues but I'm migrating my algorithm to this framework and finding issues / questions as I go along but other than that quite impressed by how it all works :)

You are helping actually. Finding bugs, and telling us about what's confusing helps us get better.

**Comment by emansammuta100533** [comment]
Re-opening as I think it still didn't fix the issue completely, I got this now on 0.0.17

`FileNotFoundError: [Errno 2] No such file or directory: 'storage/charts/BT-2020-04-18T17-48-36.png'`

**Comment by saleh-mir** [comment]
Can you please check to see if any directory or file is missing? I mean open directories in `storage/charts/BT-2020-04-18T17-48-36.png` one by one and let me know what you see.

**Comment by emansammuta100533** [comment]
> Can you please check to see if any directory or file is missing? I mean open directories in `storage/charts/BT-2020-04-18T17-48-36.png` one by one and let me know what you see.

The directory 'charts' was not created, I created the folder manually, re-ran the command and now it worked. Strange as the same for tradingview parameter created the directory & file without any manual intervention.

**Comment by saleh-mir** [comment]
That's because I was making sure to create those directories for tradingview. I missed this one. My last [commit](https://github.com/jesse-ai/jesse/commit/5f539d30b6c721c3e0eb000cab6fc0e964e3a2c0) fixes it.

**Comment by emansammuta100533** [comment]
The line needs to include exist_ok, `os.makedirs('./storage/charts', exist_ok=True) ` as it will show this error : `FileExistsError: [WinError 183] Cannot create a file when that file already exists: './storage/charts'`

**Comment by saleh-mir** [comment]
Could you please update to `0.0.19` and try again
